# This is a TOML document.


# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true



# Replace the "❯" symbol in the prompt with "→"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[→](bold green)"     # The "success_symbol" segment is being set to "→" with the color "bold green"
error_symbol = "[→](#9e4612)"

[directory]
truncation_length = 100
truncate_to_repo = false


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
